name: Build and Push Docker Images

on:
  push:
    tags:
      - '*'  # Triggers on any tag push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Extract tag name
        id: tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            berlin/eliza:latest
            berlin/eliza:${{ steps.tag.outputs.TAG }}
            438465133266.dkr.ecr.us-east-2.amazonaws.com/unicorn:latest
            438465133266.dkr.ecr.us-east-2.amazonaws.com/unicorn:${{ steps.tag.outputs.TAG }}